### PR TITLE
Add TypeScript declaration files

### PR DESCRIPTION
**Pull request by MrHertal**

### CODE REVIEW

**Comment by MrHertal** [comment]
Hi @douglasjunior,

Thanks for this well-named package.

This PR is for making your package compatible with TypeScript. If you don't want to include types directly in the repository, I can publish to the [@types organization](https://www.npmjs.com/~types) instead. You tell me :)

If you are interested, I used [this fork](https://github.com/MrHertal/react-native-recaptcha-that-works/tree/typescript) to generate the files.

**Comment by douglasjunior** [comment]
Hi @MrHertal, thanks for your help!

I dont know much about TypeScript types in a JavaScript project, but can we maintain all types in a single file named `index.d.ts`? 

The package is very small, so I think that this will make more easy to maintain.

**Comment by MrHertal** [comment]
You are right, let's put all types in a single file.

**Comment by MrHertal** [comment]
@douglasjunior I have made the changes. I also added an example usage with TypeScript in README.

**Comment by douglasjunior** [comment]
Awesome, thanks again!

**Comment by douglasjunior** [comment]
@MrHertal Sorry to abuse your skills 😄, but could you take a look at this types? https://github.com/douglasjunior/react-native-get-location/tree/types-definition

Some people are reporting problems when importing https://github.com/douglasjunior/react-native-get-location/issues/13, every help is welcome.

**Comment by MrHertal** [comment]
@douglasjunior OK 👍

I have installed the last release of your library on a React Native app with TypeScript:

`"react-native-get-location": "^2.0.0"`

I imported the lib:

`import GetLocation from "react-native-get-location";`

```tsx
  React.useEffect(() => {
    GetLocation.getCurrentPosition({
      enableHighAccuracy: true,
      timeout: 15000,
    })
      .then((location) => {
        console.log(location);
      })
      .catch((error) => {
        const { code, message } = error;
        console.warn(code, message);
      });
  }, []);
```

I get everything correctly typed and no error with TypeScript compiler. So I cannot reproduce: https://github.com/douglasjunior/react-native-get-location/issues/13#issuecomment-745466244

This guy may have an issue with his TS configuration (could be `allowSyntheticDefaultImports` not set to `true`?)

I built the app and successfully got my location (tested on iOS 14 / iPhone X).
I cannot test on Android for now, so I cannot reproduce this problem: https://github.com/douglasjunior/react-native-get-location/issues/13#issue-713414678

But it does not look like a TS problem.

**Comment by MrHertal** [comment]
@douglasjunior 

I have also tested your branch: https://github.com/douglasjunior/react-native-get-location/tree/types-definition

No error with TS compiler and types correctly set.
App built well and location is displayed.

**Comment by douglasjunior** [comment]
@MrHertal thank you very much! ❤️

**Pull request merged**
